.gitignore
src/app/store.js
src/index.js

COMO: Developer
REQUIERO: Crear un archivo .gitignore en backend y en frontend
PARA: Ignorar los archivos y carpetas que no requiero pushear a los repositorios.

OT194-134_gitignore/header

---

package.json
postcss.config.js
src/index.css
tailwind.config.js

Agregado y configurado Tailwind correctamente

OT194-135 Add Tailwind

---

src/components/Backoffice/OptionCard.jsx
src/pages/BackOfficeScreen.jsx

Añade el la pagina Backoffice el cual muestra un layout el cual en un futuro se utilizara para redireccionar a las distintas opciones de administracion. Este layout tiene unas tarjetas con diseño y animaciones agradables para la experiencia del usuario.
En la carpeta **pages** se encuentra el archivo BackOfficeScreen.jsx
* Permitir acceso a las opciones segun el rol del usuario (No posible actualmente ya que no hay conexion con back-end, ni redux configurado).
* Que cada opcion redireccione a su pagina correspondiente (No posible ya que no esta react-router instalado)

OT194-35 - Add backoffice layout

---

src/components/HomeFormAdmin/HomeFormAdmin.jsx

COMO: Usuario administrador
QUIERO: Editar los datos del Home
PARA: Mostrar el contenido correctamente
Criterios de aceptación: Este formulario permitirá editar el contenido de la página de Inicio. Contendrá un textarea para modificar el texto de Bienvenida (requerido, mínimo de 20 caracteres) y Slides (son 3, cada slide contiene una imagen y un texto)
La tarjeta no aclara nada sobre redux. Supongo que sera tarea para el futuro.
**EVIDENCIA**

OT194-37_Home Form

---

.eslintignore
.github/workflows/linter.yml

Se crea el archivo 'linter.yml' dentro de la carpeta 'github'. Se configura Github Actions para ejecutar Linter a la hora de Pushear o Mergear a la rama 'main'. Ademas, se agrega la carpeta '.github' a '.eslintignore ' para evitar conflictos.
'.github/workflows/linter.yml'  |  '.eslintignore'
Nada

Ot194 139 - Github Actions

---

.github/workflows/linter.yml

* Se arregló el error por el cual no se ejecutaba, tomando como referencia el realizado en el backend.
Ticket: https://alkemy-labs.atlassian.net/browse/OT194-144

OT194-144 Fix github action

---

src/components/NewsList/NewsList.jsx
src/components/UsersList/UsersList.jsx
src/hooks/useFetch.js

COMO: Usuario administrador
QUIERO: Listar todas las Novedades existentes
PARA: Gestionar el contenido de forma dinámica
Criterios de aceptación: Al ingresar a la ruta /backoffice/users - El administrador visualizará una tabla con el listado de los Usuarios registrados en el sitio, que serán obtenidos desde el endpoint correspondiente. En el caso de que no exista, serán mostrados desde un array. Este listado se mostrará en una tabla y contendrá las columnas nombre, apellido, email y las acciones para editar o eliminar al usuario.

OT194-51_UsersList

---

src/components/NewsList/NewsList.jsx

COMO: Desarrollador
QUIERO: Vincular el listado de Novedades con API
PARA: Mostrar el contenido dinámicamente
Criterios de aceptación: Vincular pantallas de listado y detalle con backend
EVIDENCIA

OT194-58 => news & backend

---

src/App.js
src/pages/BackOfficeTestimonials.jsx

https://alkemy-labs.atlassian.net/browse/OT194-82
Crea una pagina de Back Office en la que sera posible visualizar los testimonios existentes, con las acciones de editar y eliminar.
En **./src/pages/BackOfficeTestimonials.jsx**
Los testimonios estan mockeados.
Los botones de editar y eliminar no estan habilitados ya que todavía no existen los endpoints.

OT194-82 - Screen Listado de Testimonios (backoffice)

---

package.json
src/App.css
src/App.js
src/app/store.js
src/components/Footer/Footer.jsx
src/components/Footer/NavLinks.jsx
src/components/Footer/socialMediaLinks.jsx
src/features/organization/organizationService.js
src/features/organization/organizationSlice.js

OT194-80 Show social media at footer dynamically

---

src/pages/NewsDetail.jsx

https://alkemy-labs.atlassian.net/browse/OT194-77
Se hizo la conexion con el endpoint para visualizar la novedad si esta existe
En  ./pages/NewsDetail.jsx
Nada pendiente.

OT194-77 - Novedades: Vinculación de detalles desde endpoint

---

src/App.js
src/pages/ActivityDetail.jsx

https://alkemy-labs.atlassian.net/browse/OT194-68
Agrega la pagina necesaria para visulizar los detalles de una actividad en particular.
En ./pages/ActivityDetail.jsx
Todavia no existe el endpoint para obtener una actividad en particular

OT194-68 - Screen Detalle de Actividad

---

src/app/store.js
src/components/Contact/index.js
src/components/share/Forms/ContactForm/index.js
src/components/share/Forms/ContactForm/schemaContactForm.js
src/features/contacts/contactsSlice.js
src/helper/axiosInstance.js

https://alkemy-labs.atlassian.net/jira/software/c/projects/OT194/boards/275?modal=detail&selectedIssue=OT194-74
Se crea el slice de Contacts y la coneccion al endpoint de creacion de contacto. Además, se corrigen nombre de campos en el formulario (fullName -> name) y fix de un bug en 'axiosInstance.js'. 
'/features/contacts/contactsSlice.js'  |   '/components/Contact/index.js'  |  '/components/share/forms/ContactsForm.js'  |  
'/helpers/axiosInstance.js'
La creacion de la pagina de Contacts

OT194-74  -  Conectar screen de contacto con endpoint

---

src/App.js
src/components/Backoffice/OptionCard.jsx
src/components/Header/BurguerMenu.jsx
src/components/Header/LargeScreenMenu.jsx
src/components/Header/LoginButton.jsx
src/components/Header/LogoutButton.jsx
src/pages/BackOfficeScreen.jsx

COMO: Usuario
QUIERO: Visualizar un menú de forma dinámica
PARA: Comprender las rutas de navegación disponibles según mi rol
Criterios de aceptación: Renderizar el menú de opciones del Backoffice según el rol del usuario. Si es administrador, podrá acceder a todas las secciones de gestión (Novedades, Categorías, Testimonios, etc.), si no lo es, solamente tendrá la opción de Editar Perfil.

Ot194 62 ii

---

public/index.html
src/App.js
src/components/Footer/NavLinks.jsx
src/components/Header/BurguerMenu.jsx
src/components/Header/Header.jsx
src/components/Header/LargeScreenMenu.jsx
src/components/Header/LoginButton.jsx
src/components/Header/LogoutButton.jsx
src/components/Header/NavRoutes.jsx
src/components/Header/RegisterButton.jsx
src/components/Header/UserButton.jsx
src/components/News/index.js
src/index.css
src/pages/BackOfficeOrganization.jsx
src/pages/BackOfficeScreen.jsx
src/pages/Dashboard.jsx
src/pages/Login.jsx
src/pages/Register.jsx
src/pages/UserProfile.jsx

Ot194-102 Modify styles according to ONG logo image

---

src/App.js
src/pages/routesProtection/AdminCheck.jsx
src/pages/routesProtection/ProtectRoute.jsx

* Se crearon los componentes de protección de rutas en `src/pages/routesProtection/ProtectRoute.jsx` y `src/pages/routesProtection/AdminCheck.jsx`.
* Se implementaron en `src/App.js`.
Ticket: https://alkemy-labs.atlassian.net/browse/OT194-103

OT194-103 Protect routes considering user and user.roleId

---

src/App.js
src/components/NewsList/NewsList.jsx
src/components/share/Forms/NewsForm/index.js
src/components/share/Forms/NewsForm/schemaNewsForm.js
src/features/alert/alertSlice.js
src/features/news/newsSlice.js
src/helper/axiosInstance.js
src/pages/BackOfficeScreen.jsx
src/providers/AlertsProvider.jsx

Se modifica el reducer 'showAlert' de 'alertSlice' y los cambios necesarios en 'alertProvider' para incluir un boton de cancel. 
Se modifica el archivo 'NewsList' para incluir  a la alerta antes de borrar una novedad.
Nada
https://alkemy-labs.atlassian.net/browse/OT194-87

Ot194-87  -  Eliminar novedad desde Backoffice

---

src/App.css
src/components/Footer/Footer.jsx
src/components/Footer/NavLinks.jsx
src/components/News/index.js
src/components/share/CustomInput/index.js
src/components/share/Forms/LoginForm/index.js
src/components/share/Forms/RegisterForm/index.js
src/pages/Login.jsx
src/pages/Register.jsx
tailwind.config.js

* Se revisó y cambió el diseño de la página de login en el archivo `src/pages/Login.jsx` y modificando el formulario en `src/components/share/Forms/LoginForm/index.js`.
* Se revisó y cambió el diseño de la página de registro en el archivo `src/pages/Register.jsx` y modificando el formulario en `src/components/share/Forms/RegisterForm/index.js`.
* Se creó una clase en `src/App.css` para el control del tamaño de la imagen en ambas páginas.
* Se modificó el componente del archivo `src/components/share/CustomInput/index.js` para asemejarlo a la vista deseada y para una mejor disposición de los errores.
* Se mejoró levemente el footer para una mejor disposición de sus elementos en la versión móvil.
* Se agregó un punto de quiebre en `tailwind.config.js`.
<details>
<summary>Bosquejo de …

OT194-109 Register and login pages design revision - Footer improvement - CustomInput improvement

---

src/components/Backoffice/CardDeleteUser.jsx
src/components/NewsList/NewsList.jsx
src/features/alert/alertSlice.js
src/features/auth/authSlice.js
src/helper/axiosInstance.js
src/pages/BackOfficeScreen.jsx
src/providers/AlertsProvider.jsx

Se crea una tarjeta en el backoffice para que el usuario pueda eliminar su cuenta. Se conecta al endpoint correspondiente y se elimina los datos del usuario del state y de localStorage. Ademas, se utiliza el sliceAlert para colocar una alerta previa.
Ademas, se arregla axiosInstance para obtener el token correctamente de localStorage. 
A su vez, se debugea la alerta para realizar la accion necesaria dsp de aceptar la misma.
'pages/BackOfficeScreen'  |  'components/BackOffice/CardDeleteUser.jsx'
'features/auth/authSlice.js'  |  'helper/axiosInstance'
'features/alert/alertSlice.js'  |  'providers/AlertProvider.jsx'
'components/NewsList'
Nada
https://alkemy-labs.atlassian.net/browse/OT194-132

OT194-132  - Acción de eliminar cuenta | Fix alert News | Fix axios

---

src/components/Backoffice/CardDeleteUser.jsx
src/components/NewsList/NewsList.jsx
src/features/alert/alertSlice.js
src/features/auth/authSlice.js
src/helper/axiosInstance.js
src/pages/BackOfficeScreen.jsx
src/providers/AlertsProvider.jsx

<details>
<summary>Se persistió al usuario en el sessionStorage además del localStorage</summary>
*  Para manejar de mejor manera la navegación abriendo nuevas pestañas o ventanas.
*  Para mantener al usuario si se recarga la página.
*  Para permitir la navegar utilizando la barra de navegación.
</details>
Ticket: https://alkemy-labs.atlassian.net/browse/OT194-152

Ot194-152 Persist user in sessionStorage

---

src/components/News/index.js
src/pages/Dashboard.jsx

COMO: Usuario
QUIERO: Revisar el diseño del inicio
PARA: Verificar la adaptabilidad de la vista
Criterios de aceptación: Verificar la adaptabilidad a dispositivos móviles de los diferentes elementos y aplicar las correcciones necesarias para que pueda visualizarse correctamente. Aprovechar para terminar de refinar los elementos que se crean pertinentes

Ot194 105 Pagina de inicio Revision de diseño
